spring:
  cache:
    type: "redis"
  redis:
    host: "${REDIS_HOST:localhost}"
    port: "${REDIS_PORT:6379}"
    repositories:
      type: none
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:usho}"
    username: "${MYSQL_USER:user}"
    password: "${MYSQL_PWD:password}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    open-in-view: false

usho:
  short:
    len: 6

